channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3.1
- pip:
  - mlflow==2.6.0
  - cffi==1.16.0
  - fsspec==2023.10.0
  - numpy==1.23.5
  - packaging==23.1
  - pandas==2.1.4
  - pillow==10.0.1
  - protobuf==3.20.3
  - requests==2.31.0
  - scipy==1.11.4
  - tensorflow==2.12.0
name: mlflow-env
